# Generated by Django 4.2.6 on 2023-11-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='addres_line_2',
            new_name='address_line_2',
        ),
    ]
