# Generated by Django 4.2.6 on 2023-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=10, unique=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=200, unique=True)),
                ('images', models.ImageField(upload_to='photos/banners')),
            ],
        ),
    ]
